//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinallProject_
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference =true)]
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Images = new HashSet<Images>();
            this.Order = new HashSet<Order>();
            this.Product = new HashSet<Product>();
            this.Inbox = new HashSet<Inbox>();
            this.Inbox1 = new HashSet<Inbox>();
        }
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string First_Name { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public string Street_number { get; set; }
        [DataMember]
        public string Zip_Code { get; set; }
        [DataMember]
        public string City { get; set; }
        [DataMember]
        public string Last_Name { get; set; }
        [DataMember]
        public string UserName { get; set; }
        [DataMember]
        public string Country { get; set; }
        [DataMember]
        public string Notes { get; set; }
        [DataMember]
        public string AuthID { get; set; }
        [DataMember]
        public string ProfilePic { get; set; }
        [DataMember]
        public string AuthType { get; set; }
        [DataMember]
        public Nullable<bool> Remember { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inbox> Inbox { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inbox> Inbox1 { get; set; }
    }
}
