//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject.BuyNet {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/FinallProject_", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Images[] ImagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Inbox[] InboxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Inbox[] Inbox1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Order[] OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Product[] ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> RememberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Zip_CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthID {
            get {
                return this.AuthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthIDField, value) != true)) {
                    this.AuthIDField = value;
                    this.RaisePropertyChanged("AuthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthType {
            get {
                return this.AuthTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthTypeField, value) != true)) {
                    this.AuthTypeField = value;
                    this.RaisePropertyChanged("AuthType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Images[] Images {
            get {
                return this.ImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagesField, value) != true)) {
                    this.ImagesField = value;
                    this.RaisePropertyChanged("Images");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Inbox[] Inbox {
            get {
                return this.InboxField;
            }
            set {
                if ((object.ReferenceEquals(this.InboxField, value) != true)) {
                    this.InboxField = value;
                    this.RaisePropertyChanged("Inbox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Inbox[] Inbox1 {
            get {
                return this.Inbox1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Inbox1Field, value) != true)) {
                    this.Inbox1Field = value;
                    this.RaisePropertyChanged("Inbox1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Order[] Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Product[] Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePic {
            get {
                return this.ProfilePicField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePicField, value) != true)) {
                    this.ProfilePicField = value;
                    this.RaisePropertyChanged("ProfilePic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Remember {
            get {
                return this.RememberField;
            }
            set {
                if ((this.RememberField.Equals(value) != true)) {
                    this.RememberField = value;
                    this.RaisePropertyChanged("Remember");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street_number {
            get {
                return this.Street_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.Street_numberField, value) != true)) {
                    this.Street_numberField = value;
                    this.RaisePropertyChanged("Street_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip_Code {
            get {
                return this.Zip_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Zip_CodeField, value) != true)) {
                    this.Zip_CodeField = value;
                    this.RaisePropertyChanged("Zip_Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Images", Namespace="http://schemas.datacontract.org/2004/07/FinallProject_", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Images : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Shipping_CompaneyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((this.ProfileField.Equals(value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Shipping_CompaneyId {
            get {
                return this.Shipping_CompaneyIdField;
            }
            set {
                if ((this.Shipping_CompaneyIdField.Equals(value) != true)) {
                    this.Shipping_CompaneyIdField = value;
                    this.RaisePropertyChanged("Shipping_CompaneyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string img {
            get {
                return this.imgField;
            }
            set {
                if ((object.ReferenceEquals(this.imgField, value) != true)) {
                    this.imgField = value;
                    this.RaisePropertyChanged("img");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inbox", Namespace="http://schemas.datacontract.org/2004/07/FinallProject_", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Inbox : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.User User1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((this.ReceiverField.Equals(value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((this.SenderField.Equals(value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic {
            get {
                return this.TopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicField, value) != true)) {
                    this.TopicField = value;
                    this.RaisePropertyChanged("Topic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.User User1 {
            get {
                return this.User1Field;
            }
            set {
                if ((object.ReferenceEquals(this.User1Field, value) != true)) {
                    this.User1Field = value;
                    this.RaisePropertyChanged("User1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/FinallProject_", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuyerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.OrderProduct[] OrderProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Shipping_Company Shipping_CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SingleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> shippingIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuyerId {
            get {
                return this.BuyerIdField;
            }
            set {
                if ((this.BuyerIdField.Equals(value) != true)) {
                    this.BuyerIdField = value;
                    this.RaisePropertyChanged("BuyerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfPayment {
            get {
                return this.DateOfPaymentField;
            }
            set {
                if ((this.DateOfPaymentField.Equals(value) != true)) {
                    this.DateOfPaymentField = value;
                    this.RaisePropertyChanged("DateOfPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.OrderProduct[] OrderProduct {
            get {
                return this.OrderProductField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderProductField, value) != true)) {
                    this.OrderProductField = value;
                    this.RaisePropertyChanged("OrderProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Shipping_Company Shipping_Company {
            get {
                return this.Shipping_CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.Shipping_CompanyField, value) != true)) {
                    this.Shipping_CompanyField = value;
                    this.RaisePropertyChanged("Shipping_Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Single {
            get {
                return this.SingleField;
            }
            set {
                if ((this.SingleField.Equals(value) != true)) {
                    this.SingleField = value;
                    this.RaisePropertyChanged("Single");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> shippingId {
            get {
                return this.shippingIdField;
            }
            set {
                if ((this.shippingIdField.Equals(value) != true)) {
                    this.shippingIdField = value;
                    this.RaisePropertyChanged("shippingId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/FinallProject_", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Images[] ImagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.OrderProduct[] OrderProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SellerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((this.ConditionField.Equals(value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Feedback {
            get {
                return this.FeedbackField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedbackField, value) != true)) {
                    this.FeedbackField = value;
                    this.RaisePropertyChanged("Feedback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Images[] Images {
            get {
                return this.ImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagesField, value) != true)) {
                    this.ImagesField = value;
                    this.RaisePropertyChanged("Images");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.OrderProduct[] OrderProduct {
            get {
                return this.OrderProductField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderProductField, value) != true)) {
                    this.OrderProductField = value;
                    this.RaisePropertyChanged("OrderProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SellerId {
            get {
                return this.SellerIdField;
            }
            set {
                if ((this.SellerIdField.Equals(value) != true)) {
                    this.SellerIdField = value;
                    this.RaisePropertyChanged("SellerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/FinallProject_", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Category ParentCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Product[] ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Category[] SubCategoryCategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((this.ParentField.Equals(value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Category ParentCategory {
            get {
                return this.ParentCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentCategoryField, value) != true)) {
                    this.ParentCategoryField = value;
                    this.RaisePropertyChanged("ParentCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Product[] Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Category[] SubCategoryCategory {
            get {
                return this.SubCategoryCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoryCategoryField, value) != true)) {
                    this.SubCategoryCategoryField = value;
                    this.RaisePropertyChanged("SubCategoryCategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderProduct", Namespace="http://schemas.datacontract.org/2004/07/FinallProject_", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OrderProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Order OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceAtPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PriceAtPayment {
            get {
                return this.PriceAtPaymentField;
            }
            set {
                if ((this.PriceAtPaymentField.Equals(value) != true)) {
                    this.PriceAtPaymentField = value;
                    this.RaisePropertyChanged("PriceAtPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shipping_Company", Namespace="http://schemas.datacontract.org/2004/07/FinallProject_", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Shipping_Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Company_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Delivery_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcProject.BuyNet.Order[] OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Shipping_CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company_Name {
            get {
                return this.Company_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Company_NameField, value) != true)) {
                    this.Company_NameField = value;
                    this.RaisePropertyChanged("Company_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Delivery_Time {
            get {
                return this.Delivery_TimeField;
            }
            set {
                if ((this.Delivery_TimeField.Equals(value) != true)) {
                    this.Delivery_TimeField = value;
                    this.RaisePropertyChanged("Delivery_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcProject.BuyNet.Order[] Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Shipping_Cost {
            get {
                return this.Shipping_CostField;
            }
            set {
                if ((this.Shipping_CostField.Equals(value) != true)) {
                    this.Shipping_CostField = value;
                    this.RaisePropertyChanged("Shipping_Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string streetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.streetNumberField, value) != true)) {
                    this.streetNumberField = value;
                    this.RaisePropertyChanged("streetNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BuyNet.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        MvcProject.BuyNet.User GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.User> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users", ReplyAction="http://tempuri.org/IService1/UsersResponse")]
        MvcProject.BuyNet.User[] Users();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users", ReplyAction="http://tempuri.org/IService1/UsersResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.User[]> UsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_User", ReplyAction="http://tempuri.org/IService1/Delete_UserResponse")]
        void Delete_User(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_User", ReplyAction="http://tempuri.org/IService1/Delete_UserResponse")]
        System.Threading.Tasks.Task Delete_UserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_User", ReplyAction="http://tempuri.org/IService1/Edit_UserResponse")]
        void Edit_User(int id, MvcProject.BuyNet.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_User", ReplyAction="http://tempuri.org/IService1/Edit_UserResponse")]
        System.Threading.Tasks.Task Edit_UserAsync(int id, MvcProject.BuyNet.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategory", ReplyAction="http://tempuri.org/IService1/GetCategoryResponse")]
        MvcProject.BuyNet.Category GetCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategory", ReplyAction="http://tempuri.org/IService1/GetCategoryResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Category> GetCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        MvcProject.BuyNet.Category[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Category[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Category", ReplyAction="http://tempuri.org/IService1/Delete_CategoryResponse")]
        void Delete_Category(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Category", ReplyAction="http://tempuri.org/IService1/Delete_CategoryResponse")]
        System.Threading.Tasks.Task Delete_CategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_Category", ReplyAction="http://tempuri.org/IService1/Edit_CategoryResponse")]
        void Edit_Category(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_Category", ReplyAction="http://tempuri.org/IService1/Edit_CategoryResponse")]
        System.Threading.Tasks.Task Edit_CategoryAsync(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubCategory", ReplyAction="http://tempuri.org/IService1/SubCategoryResponse")]
        MvcProject.BuyNet.Category SubCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubCategory", ReplyAction="http://tempuri.org/IService1/SubCategoryResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Category> SubCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubCategories", ReplyAction="http://tempuri.org/IService1/SubCategoriesResponse")]
        MvcProject.BuyNet.Category[] SubCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubCategories", ReplyAction="http://tempuri.org/IService1/SubCategoriesResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Category[]> SubCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_SubCategory", ReplyAction="http://tempuri.org/IService1/Delete_SubCategoryResponse")]
        void Delete_SubCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_SubCategory", ReplyAction="http://tempuri.org/IService1/Delete_SubCategoryResponse")]
        System.Threading.Tasks.Task Delete_SubCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_SubCategory", ReplyAction="http://tempuri.org/IService1/Edit_SubCategoryResponse")]
        void Edit_SubCategory(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_SubCategory", ReplyAction="http://tempuri.org/IService1/Edit_SubCategoryResponse")]
        System.Threading.Tasks.Task Edit_SubCategoryAsync(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduct", ReplyAction="http://tempuri.org/IService1/GetProductResponse")]
        MvcProject.BuyNet.Product GetProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduct", ReplyAction="http://tempuri.org/IService1/GetProductResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Product> GetProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        MvcProject.BuyNet.Product[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducts", ReplyAction="http://tempuri.org/IService1/GetProductsResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Product[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Product", ReplyAction="http://tempuri.org/IService1/Delete_ProductResponse")]
        void Delete_Product(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Product", ReplyAction="http://tempuri.org/IService1/Delete_ProductResponse")]
        System.Threading.Tasks.Task Delete_ProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_Product", ReplyAction="http://tempuri.org/IService1/Edit_ProductResponse")]
        void Edit_Product(int id, MvcProject.BuyNet.Product pr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_Product", ReplyAction="http://tempuri.org/IService1/Edit_ProductResponse")]
        System.Threading.Tasks.Task Edit_ProductAsync(int id, MvcProject.BuyNet.Product pr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderProduct", ReplyAction="http://tempuri.org/IService1/GetOrderProductResponse")]
        MvcProject.BuyNet.OrderProduct GetOrderProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderProduct", ReplyAction="http://tempuri.org/IService1/GetOrderProductResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.OrderProduct> GetOrderProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderProducts", ReplyAction="http://tempuri.org/IService1/GetOrderProductsResponse")]
        MvcProject.BuyNet.OrderProduct[] GetOrderProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderProducts", ReplyAction="http://tempuri.org/IService1/GetOrderProductsResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.OrderProduct[]> GetOrderProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_OrderProduct", ReplyAction="http://tempuri.org/IService1/Delete_OrderProductResponse")]
        void Delete_OrderProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_OrderProduct", ReplyAction="http://tempuri.org/IService1/Delete_OrderProductResponse")]
        System.Threading.Tasks.Task Delete_OrderProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_OrderProduct", ReplyAction="http://tempuri.org/IService1/Edit_OrderProductResponse")]
        void Edit_OrderProduct(int id, MvcProject.BuyNet.OrderProduct oP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_OrderProduct", ReplyAction="http://tempuri.org/IService1/Edit_OrderProductResponse")]
        System.Threading.Tasks.Task Edit_OrderProductAsync(int id, MvcProject.BuyNet.OrderProduct oP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrder", ReplyAction="http://tempuri.org/IService1/GetOrderResponse")]
        MvcProject.BuyNet.Order GetOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrder", ReplyAction="http://tempuri.org/IService1/GetOrderResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Order> GetOrderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrders", ReplyAction="http://tempuri.org/IService1/GetOrdersResponse")]
        MvcProject.BuyNet.Order[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrders", ReplyAction="http://tempuri.org/IService1/GetOrdersResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Order[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Order", ReplyAction="http://tempuri.org/IService1/Delete_OrderResponse")]
        void Delete_Order(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Order", ReplyAction="http://tempuri.org/IService1/Delete_OrderResponse")]
        System.Threading.Tasks.Task Delete_OrderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_Order", ReplyAction="http://tempuri.org/IService1/Edit_OrderResponse")]
        void Edit_Order(int id, MvcProject.BuyNet.Order o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_Order", ReplyAction="http://tempuri.org/IService1/Edit_OrderResponse")]
        System.Threading.Tasks.Task Edit_OrderAsync(int id, MvcProject.BuyNet.Order o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        MvcProject.BuyNet.Images GetImage(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Images> GetImageAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImages", ReplyAction="http://tempuri.org/IService1/GetImagesResponse")]
        MvcProject.BuyNet.Images[] GetImages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImages", ReplyAction="http://tempuri.org/IService1/GetImagesResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Images[]> GetImagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Image", ReplyAction="http://tempuri.org/IService1/Delete_ImageResponse")]
        void Delete_Image(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Image", ReplyAction="http://tempuri.org/IService1/Delete_ImageResponse")]
        System.Threading.Tasks.Task Delete_ImageAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_Image", ReplyAction="http://tempuri.org/IService1/Edit_ImageResponse")]
        void Edit_Image(int id, MvcProject.BuyNet.Images img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_Image", ReplyAction="http://tempuri.org/IService1/Edit_ImageResponse")]
        System.Threading.Tasks.Task Edit_ImageAsync(int id, MvcProject.BuyNet.Images img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetShipping_Company", ReplyAction="http://tempuri.org/IService1/GetShipping_CompanyResponse")]
        MvcProject.BuyNet.Shipping_Company GetShipping_Company(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetShipping_Company", ReplyAction="http://tempuri.org/IService1/GetShipping_CompanyResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Shipping_Company> GetShipping_CompanyAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetShipping_Companys", ReplyAction="http://tempuri.org/IService1/GetShipping_CompanysResponse")]
        MvcProject.BuyNet.Shipping_Company[] GetShipping_Companys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetShipping_Companys", ReplyAction="http://tempuri.org/IService1/GetShipping_CompanysResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Shipping_Company[]> GetShipping_CompanysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Shipping_Company", ReplyAction="http://tempuri.org/IService1/Delete_Shipping_CompanyResponse")]
        void Delete_Shipping_Company(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Shipping_Company", ReplyAction="http://tempuri.org/IService1/Delete_Shipping_CompanyResponse")]
        System.Threading.Tasks.Task Delete_Shipping_CompanyAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_Shipping_Company", ReplyAction="http://tempuri.org/IService1/Edit_Shipping_CompanyResponse")]
        void Edit_Shipping_Company(int id, MvcProject.BuyNet.Shipping_Company ship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Edit_Shipping_Company", ReplyAction="http://tempuri.org/IService1/Edit_Shipping_CompanyResponse")]
        System.Threading.Tasks.Task Edit_Shipping_CompanyAsync(int id, MvcProject.BuyNet.Shipping_Company ship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        void AddProduct(MvcProject.BuyNet.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        System.Threading.Tasks.Task AddProductAsync(MvcProject.BuyNet.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        MvcProject.BuyNet.User LoginUser(MvcProject.BuyNet.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.User> LoginUserAsync(MvcProject.BuyNet.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dbDispose", ReplyAction="http://tempuri.org/IService1/dbDisposeResponse")]
        void dbDispose();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dbDispose", ReplyAction="http://tempuri.org/IService1/dbDisposeResponse")]
        System.Threading.Tasks.Task dbDisposeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        void AddUser(MvcProject.BuyNet.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(MvcProject.BuyNet.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddImage", ReplyAction="http://tempuri.org/IService1/AddImageResponse")]
        void AddImage(MvcProject.BuyNet.Images ima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddImage", ReplyAction="http://tempuri.org/IService1/AddImageResponse")]
        System.Threading.Tasks.Task AddImageAsync(MvcProject.BuyNet.Images ima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrderProduct", ReplyAction="http://tempuri.org/IService1/AddOrderProductResponse")]
        void AddOrderProduct(MvcProject.BuyNet.OrderProduct orderProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrderProduct", ReplyAction="http://tempuri.org/IService1/AddOrderProductResponse")]
        System.Threading.Tasks.Task AddOrderProductAsync(MvcProject.BuyNet.OrderProduct orderProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        void AddOrder(MvcProject.BuyNet.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        System.Threading.Tasks.Task AddOrderAsync(MvcProject.BuyNet.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFacebookUser", ReplyAction="http://tempuri.org/IService1/GetFacebookUserResponse")]
        MvcProject.BuyNet.User GetFacebookUser(string authId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFacebookUser", ReplyAction="http://tempuri.org/IService1/GetFacebookUserResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.User> GetFacebookUserAsync(string authId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInbox", ReplyAction="http://tempuri.org/IService1/GetInboxResponse")]
        MvcProject.BuyNet.Inbox[] GetInbox(MvcProject.BuyNet.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInbox", ReplyAction="http://tempuri.org/IService1/GetInboxResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Inbox[]> GetInboxAsync(MvcProject.BuyNet.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOutbox", ReplyAction="http://tempuri.org/IService1/GetOutboxResponse")]
        MvcProject.BuyNet.Inbox[] GetOutbox(MvcProject.BuyNet.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOutbox", ReplyAction="http://tempuri.org/IService1/GetOutboxResponse")]
        System.Threading.Tasks.Task<MvcProject.BuyNet.Inbox[]> GetOutboxAsync(MvcProject.BuyNet.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessage", ReplyAction="http://tempuri.org/IService1/AddMessageResponse")]
        void AddMessage(MvcProject.BuyNet.Inbox inbox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessage", ReplyAction="http://tempuri.org/IService1/AddMessageResponse")]
        System.Threading.Tasks.Task AddMessageAsync(MvcProject.BuyNet.Inbox inbox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddInbox", ReplyAction="http://tempuri.org/IService1/AddInboxResponse")]
        void AddInbox(MvcProject.BuyNet.Inbox inbox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddInbox", ReplyAction="http://tempuri.org/IService1/AddInboxResponse")]
        System.Threading.Tasks.Task AddInboxAsync(MvcProject.BuyNet.Inbox inbox);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MvcProject.BuyNet.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MvcProject.BuyNet.IService1>, MvcProject.BuyNet.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MvcProject.BuyNet.User GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.User> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public MvcProject.BuyNet.User[] Users() {
            return base.Channel.Users();
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.User[]> UsersAsync() {
            return base.Channel.UsersAsync();
        }
        
        public void Delete_User(int id) {
            base.Channel.Delete_User(id);
        }
        
        public System.Threading.Tasks.Task Delete_UserAsync(int id) {
            return base.Channel.Delete_UserAsync(id);
        }
        
        public void Edit_User(int id, MvcProject.BuyNet.User user) {
            base.Channel.Edit_User(id, user);
        }
        
        public System.Threading.Tasks.Task Edit_UserAsync(int id, MvcProject.BuyNet.User user) {
            return base.Channel.Edit_UserAsync(id, user);
        }
        
        public MvcProject.BuyNet.Category GetCategory(int id) {
            return base.Channel.GetCategory(id);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Category> GetCategoryAsync(int id) {
            return base.Channel.GetCategoryAsync(id);
        }
        
        public MvcProject.BuyNet.Category[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Category[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public void Delete_Category(int id) {
            base.Channel.Delete_Category(id);
        }
        
        public System.Threading.Tasks.Task Delete_CategoryAsync(int id) {
            return base.Channel.Delete_CategoryAsync(id);
        }
        
        public void Edit_Category(int id, string name) {
            base.Channel.Edit_Category(id, name);
        }
        
        public System.Threading.Tasks.Task Edit_CategoryAsync(int id, string name) {
            return base.Channel.Edit_CategoryAsync(id, name);
        }
        
        public MvcProject.BuyNet.Category SubCategory(int id) {
            return base.Channel.SubCategory(id);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Category> SubCategoryAsync(int id) {
            return base.Channel.SubCategoryAsync(id);
        }
        
        public MvcProject.BuyNet.Category[] SubCategories() {
            return base.Channel.SubCategories();
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Category[]> SubCategoriesAsync() {
            return base.Channel.SubCategoriesAsync();
        }
        
        public void Delete_SubCategory(int id) {
            base.Channel.Delete_SubCategory(id);
        }
        
        public System.Threading.Tasks.Task Delete_SubCategoryAsync(int id) {
            return base.Channel.Delete_SubCategoryAsync(id);
        }
        
        public void Edit_SubCategory(int id, string name) {
            base.Channel.Edit_SubCategory(id, name);
        }
        
        public System.Threading.Tasks.Task Edit_SubCategoryAsync(int id, string name) {
            return base.Channel.Edit_SubCategoryAsync(id, name);
        }
        
        public MvcProject.BuyNet.Product GetProduct(int id) {
            return base.Channel.GetProduct(id);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Product> GetProductAsync(int id) {
            return base.Channel.GetProductAsync(id);
        }
        
        public MvcProject.BuyNet.Product[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Product[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public void Delete_Product(int id) {
            base.Channel.Delete_Product(id);
        }
        
        public System.Threading.Tasks.Task Delete_ProductAsync(int id) {
            return base.Channel.Delete_ProductAsync(id);
        }
        
        public void Edit_Product(int id, MvcProject.BuyNet.Product pr) {
            base.Channel.Edit_Product(id, pr);
        }
        
        public System.Threading.Tasks.Task Edit_ProductAsync(int id, MvcProject.BuyNet.Product pr) {
            return base.Channel.Edit_ProductAsync(id, pr);
        }
        
        public MvcProject.BuyNet.OrderProduct GetOrderProduct(int id) {
            return base.Channel.GetOrderProduct(id);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.OrderProduct> GetOrderProductAsync(int id) {
            return base.Channel.GetOrderProductAsync(id);
        }
        
        public MvcProject.BuyNet.OrderProduct[] GetOrderProducts() {
            return base.Channel.GetOrderProducts();
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.OrderProduct[]> GetOrderProductsAsync() {
            return base.Channel.GetOrderProductsAsync();
        }
        
        public void Delete_OrderProduct(int id) {
            base.Channel.Delete_OrderProduct(id);
        }
        
        public System.Threading.Tasks.Task Delete_OrderProductAsync(int id) {
            return base.Channel.Delete_OrderProductAsync(id);
        }
        
        public void Edit_OrderProduct(int id, MvcProject.BuyNet.OrderProduct oP) {
            base.Channel.Edit_OrderProduct(id, oP);
        }
        
        public System.Threading.Tasks.Task Edit_OrderProductAsync(int id, MvcProject.BuyNet.OrderProduct oP) {
            return base.Channel.Edit_OrderProductAsync(id, oP);
        }
        
        public MvcProject.BuyNet.Order GetOrder(int id) {
            return base.Channel.GetOrder(id);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Order> GetOrderAsync(int id) {
            return base.Channel.GetOrderAsync(id);
        }
        
        public MvcProject.BuyNet.Order[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Order[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public void Delete_Order(int id) {
            base.Channel.Delete_Order(id);
        }
        
        public System.Threading.Tasks.Task Delete_OrderAsync(int id) {
            return base.Channel.Delete_OrderAsync(id);
        }
        
        public void Edit_Order(int id, MvcProject.BuyNet.Order o) {
            base.Channel.Edit_Order(id, o);
        }
        
        public System.Threading.Tasks.Task Edit_OrderAsync(int id, MvcProject.BuyNet.Order o) {
            return base.Channel.Edit_OrderAsync(id, o);
        }
        
        public MvcProject.BuyNet.Images GetImage(int id) {
            return base.Channel.GetImage(id);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Images> GetImageAsync(int id) {
            return base.Channel.GetImageAsync(id);
        }
        
        public MvcProject.BuyNet.Images[] GetImages() {
            return base.Channel.GetImages();
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Images[]> GetImagesAsync() {
            return base.Channel.GetImagesAsync();
        }
        
        public void Delete_Image(int id) {
            base.Channel.Delete_Image(id);
        }
        
        public System.Threading.Tasks.Task Delete_ImageAsync(int id) {
            return base.Channel.Delete_ImageAsync(id);
        }
        
        public void Edit_Image(int id, MvcProject.BuyNet.Images img) {
            base.Channel.Edit_Image(id, img);
        }
        
        public System.Threading.Tasks.Task Edit_ImageAsync(int id, MvcProject.BuyNet.Images img) {
            return base.Channel.Edit_ImageAsync(id, img);
        }
        
        public MvcProject.BuyNet.Shipping_Company GetShipping_Company(int id) {
            return base.Channel.GetShipping_Company(id);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Shipping_Company> GetShipping_CompanyAsync(int id) {
            return base.Channel.GetShipping_CompanyAsync(id);
        }
        
        public MvcProject.BuyNet.Shipping_Company[] GetShipping_Companys() {
            return base.Channel.GetShipping_Companys();
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Shipping_Company[]> GetShipping_CompanysAsync() {
            return base.Channel.GetShipping_CompanysAsync();
        }
        
        public void Delete_Shipping_Company(int id) {
            base.Channel.Delete_Shipping_Company(id);
        }
        
        public System.Threading.Tasks.Task Delete_Shipping_CompanyAsync(int id) {
            return base.Channel.Delete_Shipping_CompanyAsync(id);
        }
        
        public void Edit_Shipping_Company(int id, MvcProject.BuyNet.Shipping_Company ship) {
            base.Channel.Edit_Shipping_Company(id, ship);
        }
        
        public System.Threading.Tasks.Task Edit_Shipping_CompanyAsync(int id, MvcProject.BuyNet.Shipping_Company ship) {
            return base.Channel.Edit_Shipping_CompanyAsync(id, ship);
        }
        
        public void AddProduct(MvcProject.BuyNet.Product product) {
            base.Channel.AddProduct(product);
        }
        
        public System.Threading.Tasks.Task AddProductAsync(MvcProject.BuyNet.Product product) {
            return base.Channel.AddProductAsync(product);
        }
        
        public MvcProject.BuyNet.User LoginUser(MvcProject.BuyNet.User user) {
            return base.Channel.LoginUser(user);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.User> LoginUserAsync(MvcProject.BuyNet.User user) {
            return base.Channel.LoginUserAsync(user);
        }
        
        public void dbDispose() {
            base.Channel.dbDispose();
        }
        
        public System.Threading.Tasks.Task dbDisposeAsync() {
            return base.Channel.dbDisposeAsync();
        }
        
        public void AddUser(MvcProject.BuyNet.User user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(MvcProject.BuyNet.User user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public void AddImage(MvcProject.BuyNet.Images ima) {
            base.Channel.AddImage(ima);
        }
        
        public System.Threading.Tasks.Task AddImageAsync(MvcProject.BuyNet.Images ima) {
            return base.Channel.AddImageAsync(ima);
        }
        
        public void AddOrderProduct(MvcProject.BuyNet.OrderProduct orderProduct) {
            base.Channel.AddOrderProduct(orderProduct);
        }
        
        public System.Threading.Tasks.Task AddOrderProductAsync(MvcProject.BuyNet.OrderProduct orderProduct) {
            return base.Channel.AddOrderProductAsync(orderProduct);
        }
        
        public void AddOrder(MvcProject.BuyNet.Order order) {
            base.Channel.AddOrder(order);
        }
        
        public System.Threading.Tasks.Task AddOrderAsync(MvcProject.BuyNet.Order order) {
            return base.Channel.AddOrderAsync(order);
        }
        
        public MvcProject.BuyNet.User GetFacebookUser(string authId) {
            return base.Channel.GetFacebookUser(authId);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.User> GetFacebookUserAsync(string authId) {
            return base.Channel.GetFacebookUserAsync(authId);
        }
        
        public MvcProject.BuyNet.Inbox[] GetInbox(MvcProject.BuyNet.User u) {
            return base.Channel.GetInbox(u);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Inbox[]> GetInboxAsync(MvcProject.BuyNet.User u) {
            return base.Channel.GetInboxAsync(u);
        }
        
        public MvcProject.BuyNet.Inbox[] GetOutbox(MvcProject.BuyNet.User u) {
            return base.Channel.GetOutbox(u);
        }
        
        public System.Threading.Tasks.Task<MvcProject.BuyNet.Inbox[]> GetOutboxAsync(MvcProject.BuyNet.User u) {
            return base.Channel.GetOutboxAsync(u);
        }
        
        public void AddMessage(MvcProject.BuyNet.Inbox inbox) {
            base.Channel.AddMessage(inbox);
        }
        
        public System.Threading.Tasks.Task AddMessageAsync(MvcProject.BuyNet.Inbox inbox) {
            return base.Channel.AddMessageAsync(inbox);
        }
        
        public void AddInbox(MvcProject.BuyNet.Inbox inbox) {
            base.Channel.AddInbox(inbox);
        }
        
        public System.Threading.Tasks.Task AddInboxAsync(MvcProject.BuyNet.Inbox inbox) {
            return base.Channel.AddInboxAsync(inbox);
        }
    }
}
